### ISSUE TITLE
[Feature] Support Browser Environment

### ISSUE THREAD

**Issue by fabianbormann** [StricaHQ/cbors#2]
We moved recently from `lucid` to `lucid-evolution` within the `gateway` module of the `ibc-incubator` project. Unfortunately `lucid-evolution` used `cborg` for the cbor en-/ and decoding, which is not compatible with our deno "server" setup. That's why I decided to contribute to `lucid-evolution` [changing cborg with this cbors module](https://github.com/Anastasia-Labs/lucid-evolution/pull/390). While this works well for us in a local setup. The PR is still pending as the lucid-evolution team needs to support the browser target as well.

Would it be possible to build this module also for browser or using a conditional import for the `buffer` module, which is the root cause of not being able to run in a browser envionment.

Thanks for the support and the great work! 💪

**Comment by ashisherc** [comment]
@fabianbormann this package already supports browser, even used in many projects. Are you sure if its the webpack config issue with cbors and not the top level project? See webpack file, and jsDelivr for cbors

**Comment by fabianbormann** [comment]
@ashisherc Thank you for providing the quick response. I provided the Anastasia Labs team with your answer and they checked again. It seems the issue as been resolved. I will close the issue here.
